name: Deploy Laravel App to cPanel via FTP

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Set the PHP version to 8.0.30 (cPanel PHP version)

      - name: Install Dependencies
        run: |
          composer install --optimize-autoloader --no-dev
          npm install
          npm run build # If you have any front-end assets

      - name: Deploy via FTP
        uses: SamKirkland/ftp-deploy-action@v4
        with:
          server: poultrymasterbd.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./ # This points to your repository root directory
          server-dir: /home/poultrym/poultrymasterbd.com  # cPanel deployment directory
          log-level: verbose
